version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'

  app:
    build: .
    working_dir: /app/preview
    command: './startup.sh'
    env_file:
      - .env.function
      - .env.view
    ports:
      - 5000:5000
    volumes:
      - ./:/app/preview
      - /usr/share/container_build:/app/preview/._bb_/container_build
      - /usr/share/elements_build:/app/preview/._bb_/elements_emulator/dist
    depends_on:
      - postgres
      - redis

volumes:
  cache:
